import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Component_Header from "@/components/templates/structure/header/Component_Header";
import Component_Main from "@/components/templates/structure/main/Component_Main";
import NavBar from "@/components/templates/structure/navbar/Component_NavBar";
import Component_Footer from "@/components/templates/structure/footer/Component_Footer";

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col w-full h-max`}
      >
      
        <Component_Header />      

        <Component_Main>
  
          <NavBar />
          
          {children}

        </Component_Main>

        <Component_Footer />

      </body>
    </html>
  );
}
